version: 2

sources:
  - name: raw
    database: assessment  
    schema: raw          
    tables:
      - name: order_line_items
      - name: orders
      - name: customers
      - name: employees
      - name: products
      - name: returns

