
version: 2

models:
  - name: report_store_performance
    description: "Report summarizing store performance metrics for sales analysis and operational insights."
    columns:
      - name: store_id
        description: "Unique identifier for each store."
        tests:
          - unique
          - not_null
      - name: store_name
        description: "Name of the store."
      - name: location
        description: "Geographical location of the store."
      - name: total_employees
        description: "Total number of employees in the store."
      - name: total_units_sold
        description: "Total number of units sold in the store."
      - name: total_customers
        description: "Total number of unique customers for the store."
      - name: total_orders
        description: "Total number of orders placed in the store."
      - name: returned_order_counts
        description: "Total number of returned orders (zero if none)."
      - name: total_sales_amount
        description: "Total revenue generated by the store."
      - name: average_order_value
        description: "Average order value for the store."
      - name: store_type
        description: "Category of the store (e.g., flagship, outlet, etc.)."

  - name: report_customer_behavior
    description: "Report analyzing customer behavior, loyalty, and spending patterns."
    columns:
      - name: customer_id
        description: "Unique identifier for each customer."
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Full name of the customer."
      - name: gender
        description: "Gender of the customer."
      - name: age_group
        description: "Categorized age group of the customer (below 18, 18-30, 31-45, 46-60, above 60)."
      - name: membership_level
        description: "Loyalty program membership status."
      - name: total_orders
        description: "Total number of orders placed by the customer."
      - name: average_order_value
        description: "Average value of the customer's orders."
      - name: number_of_returns
        description: "Total number of returns made by the customer."
      - name: last_order_date
        description: "Date of the customer's most recent order."
      - name: customer_tenure
        description: "Number of years the customer has been with the company."
      - name: total_return
        description: "Total number of products returned by the customer."
      - name: total_return_amount
        description: "Total monetary value of the customer's returned orders."
      - name: total_discount_used
        description: "Total discount availed by the customer."

